#!/usr/bin/env bash
# changelog.sh - Generate CHANGELOG.md from git history
set -euo pipefail

REPO="${PWD}"; SINCE=""; OUTPUT="CHANGELOG.md"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="$2"; shift 2 ;;
    --since) SINCE="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    --help|-h) echo "Usage: bash changelog.sh [--repo /path] [--since tag]"; exit 0 ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done

cd "$REPO"
[[ -z "$SINCE" ]] && SINCE="$(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)"
echo "Generating changelog from $SINCE..."

ADDED=(); FIXED=(); CHANGED=(); REMOVED=()
while IFS= read -r line; do
  msg="$(echo "$line" | sed -E 's/^[0-9a-f]{7,40} //')"
  type="$(echo "$msg" | sed -E 's/^([a-zA-Z]+)[:(].*//' | tr '[:upper:]' '[:lower:]')"
  desc="$(echo "$msg" | sed -E 's/^[a-zA-Z]+[:(]?[[:space:]]*//')"
  case "$type" in
    feat|feature|add|new) ADDED+=("$desc") ;;
    fix|bugfix|hotfix|bug) FIXED+=("$desc") ;;
    refactor|update|change|improve|perf) CHANGED+=("$desc") ;;
    remove|drop|delete|deprecate) REMOVED+=("$desc") ;;
    *) CHANGED+=("$desc") ;;
  esac
done < <(git log "${SINCE}..HEAD" --oneline --no-decorate 2>/dev/null || true)

{
  echo "# Changelog"; echo ""
  echo "## [$(date +%Y-%m-%d)]"; echo ""
  if [[ ${#ADDED[@]} -gt 0 ]]; then
    echo "### Added"; for i in "${ADDED[@]}"; do echo "- $i"; done; echo ""
  fi
  if [[ ${#FIXED[@]} -gt 0 ]]; then
    echo "### Fixed"; for i in "${FIXED[@]}"; do echo "- $i"; done; echo ""
  fi
  if [[ ${#CHANGED[@]} -gt 0 ]]; then
    echo "### Changed"; for i in "${CHANGED[@]}"; do echo "- $i"; done; echo ""
  fi
  if [[ ${#REMOVED[@]} -gt 0 ]]; then
    echo "### Removed"; for i in "${REMOVED[@]}"; do echo "- $i"; done; echo ""
  fi
  echo "---"; echo "*Generated by changelog.sh*"
} > "$OUTPUT"
echo "Done: $OUTPUT ($(wc -l < "$OUTPUT") lines)"
