#!/usr/bin/env python3
"""claude-review — PR review sub-agent that posts structured comments
Usage: claude-review --pr https://github.com/owner/repo/pull/123 [--github-token xxx]
"""
import argparse, json, urllib.request, re, os, sys
from urllib.parse import urlparse

def parse_pr_url(url):
    m = re.search(r"github\.com/([^/]+)/([^/]+)/pull/(\d+)", url)
    if not m: raise ValueError("Invalid PR URL")
    return m.group(1), m.group(2), int(m.group(3))

def get_pr_diff(owner, repo, number, token):
    req = urllib.request.Request(
        f"https://api.github.com/repos/{owner}/{repo}/pulls/{number}",
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3.diff"}
    )
    return urllib.request.urlopen(req, timeout=30).read().decode()

def get_pr_metadata(owner, repo, number, token):
    req = urllib.request.Request(
        f"https://api.github.com/repos/{owner}/{repo}/pulls/{number}",
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3+json"}
    )
    return json.loads(urllib.request.urlopen(req, timeout=15).read())

def analyze_diff(diff):
    files_changed = len(re.findall(r"^diff --git a/", diff, re.MULTILINE))
    lines_added = len(re.findall(r"^\+[^+]", diff, re.MULTILINE))
    lines_removed = len(re.findall(r"^-[^-]", diff, re.MULTILINE))
    return {"files_changed": files_changed, "lines_added": lines_added, "lines_removed": lines_removed}

def review_pr(owner, repo, number, token):
    meta = get_pr_metadata(owner, repo, number, token)
    diff = get_pr_diff(owner, repo, number, token)
    stats = analyze_diff(diff)
    
    title = meta.get("title", "")
    body = (meta.get("body") or "")[:500]
    author = meta.get("user", {}).get("login", "unknown")
    
    review = f"""## PR Review: {title}

**Author:** @{author} | **Files:** {stats['files_changed']} | **+{stats['lines_added']}/-{stats['lines_removed']}

### Summary
{body[:300]}

### Checklist
- [ ] Code style matches project conventions
- [ ] No secrets/credentials in diff
- [ ] Error handling is present
- [ ] Tests included (if applicable)
- [ ] Breaking changes documented

### Files Changed
{stats['files_changed']} files, +{stats['lines_added']} / -{stats['lines_removed']} lines

---
*Generated by claude-review*
"""
    return review

def main():
    parser = argparse.ArgumentParser(description="Review a GitHub PR")
    parser.add_argument("--pr", required=True, help="PR URL")
    parser.add_argument("--github-token", default=os.environ.get("GITHUB_TOKEN", ""), help="GitHub token")
    args = parser.parse_args()
    token = args.github_token or os.environ.get("GITHUB_TOKEN", "")
    if not token: print("Error: GITHUB_TOKEN required"); sys.exit(1)
    owner, repo, number = parse_pr_url(args.pr)
    print(review_pr(owner, repo, number, token))

if __name__ == "__main__":
    main()
